version: '3.4'
services:

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
#    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TORRENTS}:/data # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files
    ports:
      - 9117:9117
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9117"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
#    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${TVSHOWS}:/tv
      - ${TORRENTS}:/data
    ports:
      - 8989:8989
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8989"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
#    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config
      - ${MOVIES}:/movies
      - ${TVSHOWS}:/tv
#      - ${MOVIESHD}:/movies/HD
#      - ${ANIME}:/movies/Animacion
#      - ${MOVIES3D}:/movies/3D      
      - ${TORRENTS}:/data # download folder
    ports:
      - 7878:7878
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:7878"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config
      - ${MOVIES}:/movies
      - ${TVSHOWS}:/tv
    ports:
      - 6767:6767
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:6767"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s
